FROM node:20-slim

RUN useradd -u 17218 p2proxy

ENV WORKDIR=/home/p2proxy/ 

COPY node_modules ${WORKDIR}/node_modules
COPY package-lock.json ${WORKDIR}
COPY package.json ${WORKDIR}
COPY index.js ${WORKDIR}
COPY client.js ${WORKDIR}

USER p2proxy

ENTRYPOINT ["/home/p2proxy/client.js"]
